angular.module('ngAppGyorsFutar',
    [   'ui.router',
        'ui.bootstrap',
        'ngStorage',
        'ngModuleLocation',
        'ngModuleBkkFutar',
        'ngModuleLocationDetection',
        'ngModuleRecentLocationList',
        'ngModuleLocationPicker',
        'ngModuleTimetable',
        'ngModuleTrip']);
