angular.module('ngAppGyorsFutar',
    [   'ui.router',
        'ui.bootstrap',
        'uiGmapgoogle-maps',
        'ngStorage',
        'ngMaterial',
        'ngModuleLocation',
        'ngModuleBkkFutar',
        'ngModuleLocationDetection',
        'ngModuleRecentLocationList',
        'ngModuleLocationPicker',
        'ngModuleTimetable',
        'ngModuleTrip',
        'ngModuleSchedule',
        'ngModuleMap']);
