angular
    .module('ngModuleBkkFutar', [])
    .constant('BKK_FUTAR', {
        'HTTP_JSONP_REQUEST_TIMEOUT': 5000,

        'PARAM_NAME_JSONP_CALLBACK': 'callback',
        'PARAM_VALUE_JSONP_CALLBACK': 'JSON_CALLBACK',

        'URL_API_BASE': 'http://futar.bkk.hu/bkk-utvonaltervezo-api/ws/otp/api/where/',
        'PARAM_API_BASE_REFERENCES': '$INCLUDE_REFERENCES',
        'PARAM_NAME_API_BASE_REFERENCES': 'includeReferences',

        'URL_API_SEARCH': 'search.json',
        'PARAM_API_SEARCH_QUERY': 'query',
        'PARAM_VALUE_API_SEARCH_REFERENCES': 'routes,stops',

        'URL_API_STOPS_FOR_LOCATION': 'stops-for-location.json',
        'PARAM_NAME_API_STOPS_FOR_LOCATION_LATITUDE': 'lat',
        'PARAM_NAME_API_STOPS_FOR_LOCATION_LONGITUDE': 'lon',
        'PARAM_NAME_API_STOPS_FOR_LOCATION_RADIUS': 'radius',
        'PARAM_VALUE_API_STOPS_FOR_LOCATION_REFERENCES': 'false',

        'URL_API_ARRIVALS_AND_DEPARTURES_FOR_STOP': 'arrivals-and-departures-for-stop.json',
        'PARAM_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_STOP_IDS': 'stopId',
        'PARAM_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_ONLY_DEPARTURES': 'onlyDepartures',
        'PARAM_VALUE_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_ONLY_DEPARTURES': 'false',
        'PARAM_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_MINUTES_BEFORE': 'minutesBefore',
        'PARAM_VALUE_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_MINUTES_BEFORE': '0',
        'PARAM_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_MINUTES_AFTER': 'minutesAfter',
        'PARAM_VALUE_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_MINUTES_AFTER': '30',
        'PARAM_VALUE_API_ARRIVALS_AND_DEPARTURES_FOR_STOP_REFERENCES': 'trips',

        'URL_API_TRIP_DETAILS': 'trip-details.json',
        'PARAM_API_TRIP_DETAILS_TRIP_ID': 'tripId',
        'PARAM_VALUE_API_TRIP_DETAILS_REFERENCES': 'routes,stops,trips',

        'URL_API_SCHEDULE_FOR_STOP': 'schedule-for-stop.json',
        'PARAM_API_SCHEDULE_FOR_STOP_STOP_ID': 'stopId',
        'PARAM_API_SCHEDULE_FOR_STOP_ONLY_DEPARTURES': 'onlyDepartures',
        'PARAM_VALUE_API_SCHEDULE_FOR_STOP_ONLY_DEPARTURES': 'true',
        'PARAM_API_SCHEDULE_FOR_STOP_DATE': 'date',
        'PARAM_VALUE_API_SCHEDULE_FOR_STOP_REFERENCES': 'routes,stops',

        'PARAM_VALUE_API_SCHEDULE_FOR_STOPS_ONLY_DEPARTURES': 'true',
        'PARAM_VALUE_API_SCHEDULE_FOR_STOPS_REFERENCES': 'false',

        'REGEXP_ROUTE_ID_NIGHT_TRANSPORT': /^BKK_9.*/
    });
